# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMenginputkontenpencarian():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_menginputkontenpencarian(self):
    # Test name: Menginput konten pencarian
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.facebook.com/")
    # 2 | setWindowSize | 656x680 | 
    self.driver.set_window_size(656, 680)
    # 3 | click | css=.x1fns5xo | 
    self.driver.find_element(By.CSS_SELECTOR, ".x1fns5xo").click()
    # 4 | mouseOver | css=#mobile\ legends\3A\ bang\ bang .x193iq5w > .x1lliihq | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#mobile\\ legends\\3A\\ bang\\ bang .x193iq5w > .x1lliihq")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | click | css=#mobile\ legends\3A\ bang\ bang .x193iq5w > .x1lliihq | 
    self.driver.find_element(By.CSS_SELECTOR, "#mobile\\ legends\\3A\\ bang\\ bang .x193iq5w > .x1lliihq").click()
    # 6 | mouseOver | css=.xu06os2:nth-child(2) > .xudqn12 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".xu06os2:nth-child(2) > .xudqn12")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.xu06os2:nth-child(2) > .xudqn12 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | mouseOver | css=.x1qjc9v5 > .xqtp20y .xz74otr | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".x1qjc9v5 > .xqtp20y .xz74otr")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
