# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHanyamengisidataemaildanmengosongkandatapassword():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hanyamengisidataemaildanmengosongkandatapassword(self):
    # Test name: Hanya mengisi data email dan mengosongkan data password
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.facebook.com/")
    # 2 | setWindowSize | 654x680 | 
    self.driver.set_window_size(654, 680)
    # 3 | type | id=email | tobecontinue
    self.driver.find_element(By.ID, "email").send_keys("tobecontinue")
    # 4 | click | id=u_0_5_Zz | 
    self.driver.find_element(By.ID, "u_0_5_Zz").click()
    # 5 | assertText | id=header_block | Log in to Facebook
    assert self.driver.find_element(By.ID, "header_block").text == "Log in to Facebook"
    # 6 | verifyText | css=.\_9axz | Log in to Facebook
    assert self.driver.find_element(By.CSS_SELECTOR, ".\\_9axz").text == "Log in to Facebook"
    # 7 | close |  | 
    self.driver.close()
  
